base_instructions = [
    { name = "Adc", pattern = "011???01" },
    { name = "And", pattern = "001???01" },
    { name = "Asl", pattern = "000??110,00001?10" },
    { name = "Bcc", pattern = "10010000" },
    { name = "Bcs", pattern = "10110000" },
    { name = "Beq", pattern = "11110000" },
    { name = "Bit", pattern = "0010?100" },
    { name = "Bmi", pattern = "00110000" },
    { name = "Bne", pattern = "11010000" },
    { name = "Bpl", pattern = "00010000" },
    { name = "Brk", pattern = "00000000" },
    { name = "Bvc", pattern = "01010000" },
    { name = "Bvs", pattern = "01110000" },
    { name = "Clc", pattern = "00011000" },
    { name = "Cld", pattern = "11011000" },
    { name = "Cli", pattern = "01011000" },
    { name = "Clv", pattern = "10111000" },
    { name = "Cmp", pattern = "110???01" },
    { name = "Cpx", pattern = "11100?00,1110?100" },
    { name = "Cpy", pattern = "11000?00,1100?100" },
    { name = "Dec", pattern = "110??110" },
    { name = "Dex", pattern = "11001010" },
    { name = "Dey", pattern = "10001000" },
    { name = "Eor", pattern = "010???01" },
    { name = "Inc", pattern = "111??110" },
    { name = "Inx", pattern = "11101000" },
    { name = "Iny", pattern = "11001000" },
    { name = "Jmp", pattern = "01?01100" },
    { name = "Jsr", pattern = "00100000" },
    { name = "Lda", pattern = "101???01" },
    { name = "Ldx", pattern = "10100?10,101??110" },
    { name = "Ldy", pattern = "10100?00,101??100" },
    { name = "Lsr", pattern = "010??110,01001?10" },
    { name = "Nop", pattern = "100000?0,11?00010,000??100,0??1?100,01??0100,?1?1?100,10001001,0??11010,11?11010,111?1010" },
    { name = "Ora", pattern = "000???01" },
    { name = "Pha", pattern = "01001000" },
    { name = "Php", pattern = "00001000" },
    { name = "Pla", pattern = "01101000" },
    { name = "Plp", pattern = "00101000" },
    { name = "Rol", pattern = "001??110,00101?10" },
    { name = "Ror", pattern = "011??110,01101?10" },
    { name = "Rti", pattern = "01000000" },
    { name = "Rts", pattern = "01100000" },
    { name = "Sbc", pattern = "111???01" },
    { name = "Sec", pattern = "00111000" },
    { name = "Sed", pattern = "11111000" },
    { name = "Sei", pattern = "01111000" },
    { name = "Sta", pattern = "100?0?01,100??101,1001??01" },
    { name = "Stx", pattern = "100?0110,1000?110" },
    { name = "Sty", pattern = "100?0100,1000?100" },
    { name = "Tax", pattern = "10101010" },
    { name = "Tay", pattern = "10101000" },
    { name = "Tsx", pattern = "10111010" },
    { name = "Txa", pattern = "10001010" },
    { name = "Txs", pattern = "10011010" },
    { name = "Tya", pattern = "10011000" },

    { name = "Alr", pattern = "01001011" },
    { name = "Anc", pattern = "00?01011" },
    { name = "Ane", pattern = "10001011" },
    { name = "Arr", pattern = "01101011" },
    { name = "Dcp", pattern = "110?0?11,110??111,1101??11" },
    { name = "Isc", pattern = "111?0?11,111??111,1111??11" },
    { name = "Las", pattern = "10111011" },
    { name = "Lax", pattern = "101?0?11,101??111" },
    { name = "Lxa", pattern = "10101011" },
    { name = "Rla", pattern = "001?0?11,001??111,0011??11" },
    { name = "Rra", pattern = "011?0?11,011??111,0111??11" },
    { name = "Sax", pattern = "10000?11,1000?111,100?0111" },
    { name = "Sbx", pattern = "11001011" },
    { name = "Sha", pattern = "10010011,10011111" },
    { name = "Shx", pattern = "10011110" },
    { name = "Shy", pattern = "10011100" },
    { name = "Slo", pattern = "000?0?11,000??111,0001??11" },
    { name = "Sre", pattern = "010?0?11,010??111,0101??11" },
    { name = "Tas", pattern = "10011011" },
    { name = "Usbc", pattern = "11101011" },
    { name = "Jam", pattern = "0???0010,???10010" },
]

addressing_modes = [
    { name = "A", pattern = "0??01010" },
    { name = "Abs", pattern = "00100000,00?011??,010011??,1??011??,???01101,???0111?" },
    { name = "AbsIdx", pattern = "???11??1,???111??" },
    { name = "Imm", pattern = "1??000?0,???010?1" },
    { name = "Impl", pattern = "0000?000,01?0?000,????1000,???110?0,1???10?0" },
    { name = "Ind", pattern = "01101100" },
    { name = "XInd", pattern = "???000?1" },
    { name = "IndY", pattern = "???100?1" },
    { name = "Rel", pattern = "???10000" },
    { name = "Zpg", pattern = "???001??" },
    { name = "ZpgIdx", pattern = "???101??" },
]

addressing_mode_registers = [
    { name = "X", pattern = "0??1?1??,???1?10?,11?1?1??" },
    { name = "Y", pattern = "???110?1,10?1?11?" },
]
